version: '3.9'
networks:
  traefik-net:
    external: true
services:
  model-api-opusmt:
    container_name: model-api-opusmt
    image: model-api-opusmt
    build:
      context: ./code
      dockerfile: Dockerfile.prod
    working_dir: /app
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
    ports:
      - "8011:80"
    networks:
      - traefik-net
    command: [ "uvicorn", "main:app", "--host", "0.0.0.0", "--debug", "--port", "80", "--reload-dir", "/app" ]
    volumes:
      - ./code/app:/app
    labels:
      - "traefik.enable=true"
      - "traefik.port=8088" # port of the traefik instance
      - "traefik.docker.network=traefik-net" # traefik network
      - "traefik.http.routers.model-api-opusmt.entrypoints=websecure"
      - "traefik.http.routers.model-api-opusmt.rule=PathPrefix(`/opus`)" # URL path to your backend, replace YOUR-BACKEND with an unique string to name your router
      - "traefik.http.routers.model-api-opusmt.tls=true"
      - "traefik.http.middlewares.strip-opus-mt.stripprefix.prefixes=/opus" # declare strip prefix middleware from above, replace strip-YOUR-PATH with an unique name
      - "traefik.http.routers.model-api-opusmt.middlewares=strip-opus-mt@docker"
