version: '3.7'
networks:
  study-align-model-network:
    driver: bridge
services:
  study-align-model-t5:
    container_name: study-align-model-t5
    image: study-align-model-t5
    build: code
    ports:
      - "8009:80"
    networks:
      - study-align-model-network
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--debug", "--port", "80", "--reload-dir", "/app"]
    volumes:
      - ./code/app:/app
  nginx:
    container_name: study-align-model-t5-nginx
    image: nginx:1.19.0-alpine
    volumes:
      - ./loadbalancer/nginx.conf:/etc/nginx/conf.d/default.conf 
#      - ./nginx/error.log:/etc/nginx/error_log.log
#      - ./nginx/cache/:/etc/nginx/cache
#      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 8090:8080
    #  - 444:443
    depends_on:
      - study-align-model-t5
    networks:
      - study-align-model-network
    
